# Generated by Django 5.1.3 on 2024-12-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_description',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='video_title',
            field=models.CharField(max_length=40),
        ),
    ]
