# Generated by Django 5.1.3 on 2024-12-05 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videomodel_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_id',
            field=models.UUIDField(default=uuid.UUID('4605ee15-329e-4f75-b025-d090db6ff7da'), editable=False, unique=True),
        ),
    ]
