# Generated by Django 5.1.3 on 2024-12-05 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videomodel_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_id',
            field=models.UUIDField(default=uuid.UUID('ea7fe273-dad1-4d4e-aad0-cb6a3604f4ca'), editable=False, unique=True),
        ),
    ]
