# Generated by Django 5.1.3 on 2024-12-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_videomodel_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='video_id',
        ),
    ]
