# Generated by Django 5.1.3 on 2024-12-05 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_videomodel_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_id',
            field=models.UUIDField(default=uuid.UUID('47a76b54-48d1-492b-a04f-9898b339bd45'), editable=False, unique=True),
        ),
    ]
