# Generated by Django 5.1.3 on 2024-12-05 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_videomodel_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_src',
            field=models.FileField(upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
