# Generated by Django 5.1.3 on 2024-12-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_videomodel_video_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='videos_uploaded/video_thumbnails'),
        ),
    ]
