# Generated by Django 5.1.3 on 2024-12-12 15:02

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_alter_videomodel_video_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_thumb',
            field=models.ImageField(blank=True, null=True, upload_to=videos.models.gen_folder),
        ),
    ]
