# Generated by Django 5.1.3 on 2024-12-13 18:06

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_videomodel_video_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_thumb',
            field=models.ImageField(upload_to=videos.models.gen_folder),
        ),
    ]
