# Generated by Django 5.1.3 on 2024-12-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_videomodel_video_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='video_thumb',
        ),
    ]
