# Generated by Django 5.1.3 on 2024-12-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_remove_videomodel_video_thumb'),
        ('videos', '0013_alter_videomodel_video_thumb'),
    ]

    operations = [
    ]
