# Generated by Django 5.1.3 on 2024-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_videomodel_video_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_view',
            field=models.IntegerField(default=0),
        ),
    ]
