# Generated by Django 5.1.3 on 2024-12-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_remove_videomodel_video_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_view',
            field=models.IntegerField(default=0),
        ),
    ]
