# Generated by Django 5.1.3 on 2024-12-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_videomodel_video_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='video_view',
        ),
    ]
