# Generated by Django 5.1.3 on 2024-12-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_remove_videomodel_video_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='video_description',
            new_name='video_desc',
        ),
    ]
