# Generated by Django 5.1.3 on 2024-12-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_alter_commentmodel_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videomodel'),
        ),
    ]
