# Generated by Django 5.1.3 on 2024-12-20 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_alter_commentmodel_comment_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment_video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.videomodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
