# Generated by Django 5.1.3 on 2024-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_commentmodel_comment_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='video_likes',
            field=models.IntegerField(default=0),
        ),
    ]
