# Generated by Django 5.1.3 on 2024-12-30 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_videomodel_video_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_comment_text', models.TextField(max_length=100)),
                ('reply_comment_date', models.DateField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_video', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.videomodel')),
                ('reply_comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.commentmodel')),
            ],
        ),
    ]
