# Generated by Django 5.1.3 on 2024-12-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profilemodel_user_picture'),
        ('videos', '0027_commentreplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profilemodel'),
        ),
    ]
