# Generated by Django 5.1.3 on 2024-12-30 17:07

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profilemodel_user_picture'),
        ('videos', '0028_commentmodel_comment_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profilemodel'),
        ),
    ]
