# Generated by Django 5.1.3 on 2025-04-01 20:58

import django.core.validators
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0032_commentmodel_comment_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_src',
            field=models.FileField(upload_to=videos.models.gen_folder, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov'])]),
        ),
    ]
