# Generated by Django 5.1.3 on 2025-06-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0033_alter_videomodel_video_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='comment_picture',
        ),
    ]
