# Generated by Django 5.1.3 on 2025-06-01 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_followmodel'),
        ('videos', '0035_commentmodel_comment_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profilemodel'),
        ),
    ]
