# Generated by Django 5.1.3 on 2025-06-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0036_alter_commentmodel_comment_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='comment_picture',
        ),
    ]
