# Generated by Django 5.1.3 on 2025-06-02 16:41

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0037_remove_commentmodel_comment_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_thumb',
            field=models.ImageField(default='thumbnails/default_thumbnail.png', upload_to=videos.models.gen_folder),
        ),
    ]
