# Generated by Django 5.1.3 on 2025-06-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0038_alter_videomodel_video_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_date',
            field=models.DateField(auto_now=True),
        ),
    ]
