# Generated by Django 5.1.3 on 2025-06-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0039_alter_videomodel_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='video_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
