# Generated by Django 5.1.3 on 2025-06-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0040_alter_videomodel_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
