# Generated by Django 5.1.3 on 2024-12-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='user_desc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
