# Generated by Django 5.1.3 on 2024-12-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='user_banner',
            field=models.ImageField(default='', upload_to='profile_images/'),
        ),
    ]
