# Generated by Django 5.1.3 on 2024-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilemodel_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='user_banner',
            field=models.ImageField(default='default/banner-5185316.jpg', upload_to='profile_images/'),
        ),
    ]
