# Generated by Django 5.1.3 on 2024-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profilemodel_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='user_picture',
            field=models.ImageField(default='default/Default_pfp.jpg', upload_to='profile_images'),
        ),
    ]
