# Generated by Django 5.1.3 on 2025-03-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_followmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowModel',
        ),
    ]
