# Generated by Django 5.1.3 on 2025-06-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_followmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='user_followers',
            field=models.IntegerField(default=0),
        ),
    ]
