# Generated by Django 5.1.3 on 2025-06-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profilemodel_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='user_following',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FollowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_follow_date', models.DateTimeField(auto_now_add=True)),
                ('user_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.profilemodel')),
                ('user_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.profilemodel')),
            ],
        ),
    ]
