# Generated by Django 5.1.3 on 2025-06-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profilemodel_user_following_followmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='user_followers',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='user_following',
        ),
        migrations.DeleteModel(
            name='FollowModel',
        ),
    ]
